<!DOCTYPE html>
<html>
<head><title>WELCOME!!</title>
</head>
<body bgcolor="teal">
<font face="monotype corsiva" color="#00008b">
<center><img src="congrats.jpg" height="500" width="500"></center> 
<form name="fname" onsubmit="return validate()">
<?php
session_start();
$m=0;
if(isset($_POST["q1"]))
{
if($_POST["q1"]=="d")
{
$m+=1;
}}
if(isset($_POST["q2"]))
{
if($_POST["q2"]=="c")
{
$m+=1;
}}
if(isset($_POST["q3"]))
{
if($_POST["q3"]=="b")
{
$m+=1;
}}
if(isset($_POST["q4"]))
{
if($_POST["q4"]=="b")
{
$m+=1;
}}
if(isset($_POST["q5"]))
{
if($_POST["q5"]=="c")
{
$m+=1;
}}
if(isset($_POST["q6"]))
{
if($_POST["q6"]=="a")
{
$m+=1;
}}
if(isset($_POST["q7"]))
{
if($_POST["q7"]=="d")
{
$m+=1;
}}
if(isset($_POST["q8"]))
{
if($_POST["q8"]=="b")
{
$m+=1;
}}
if(isset($_POST["q9"]))
{
if($_POST["q9"]=="c")
{
$m+=1;
}}
if(isset($_POST["q10"]))
{
if($_POST["q10"]=="d")
{
$m+=1;
}}
if(isset($_POST["q11"]))
{
if($_POST["q11"]=="d")
{
$m+=1;
}}
if(isset($_POST["q12"]))
{
if($_POST["q12"]=="d")
{
$m+=1;
}}
if(isset($_POST["q13"]))
{
if($_POST["q13"]=="c")
{
$m+=1;
}}
if(isset($_POST["q14"]))
{
if($_POST["q14"]=="b")
{
$m+=1;
}}
if(isset($_POST["q15"]))
{
if($_POST["q15"]=="a")
{
$m+=1;
}
}

$con=new mysqli("localhost","root","","innolog");
$rn=$_SESSION["reg_no"];
$name=$_SESSION["name"];
$sql="INSERT INTO innolog.mcq(REG_NO,NAME,MARKS)VALUES('$rn','$name','$m')";
$con->query($sql);
echo"<h1><b><center>CONGRATULATIONS FOR COMPLETING THE TEST!!!</center></b></h1>";
echo"<br>";
echo"<center><h1>";
echo"YOUR RESULT IS:$m";
echo"</center></h1>";
echo"<br>";echo"<br>";
?>
</font>
</body>
</html>